<?php

return [
    [
        "title" => "My Project",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-10",
        "last_update" => "2023-02-11",
        "collaborators" => "No",
        "image" => "img/planet.png",
        "description" => "The first project",
        "technologies" => [1],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/Myproject.git",
    ],

    [
        "title" => "Hello",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-23",
        "last_update" => "2023-02-23",
        "collaborators" => "No",
        "image" => "uploads/hello.png",
        "description" => "The hello project",
        "technologies" => [1],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/htmlcss-hello.git",
    ],

    [
        "title" => "London Trip",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-24",
        "last_update" => "2023-02-27",
        "collaborators" => "No",
        "image" => "uploads/london.png",
        "description" => "My travel for London",
        "technologies" => [1],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-london-trip.git",
    ],

    [
        "title" => "Booleaner",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-27",
        "last_update" => "2023-03-01",
        "collaborators" => "No",
        "image" => "uploads/booleaner.png",
        "description" => "The Booleaner",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-booleaner.git",
    ],

    [
        "title" => "Toboolist",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-28",
        "last_update" => "2023-03-01",
        "collaborators" => "No",
        "image" => "uploads/toboolist.png",
        "description" => "The Toboolist",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-toboolist.git",
    ],

    [
        "title" => "Float Cards",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-02",
        "last_update" => "2023-03-02",
        "collaborators" => "No",
        "image" => "uploads/floatcards.png",
        "description" => "The Floats Cards",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-float-cards.git",
    ],

    [
        "title" => "Struttura Discord",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-06",
        "last_update" => "2023-03-06",
        "collaborators" => "No",
        "image" => "uploads/strutturadiscord.png",
        "description" => "A first structure of site Discord",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/htmlcss-struttura-discord.git",
    ],

    [
        "title" => "Discord",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-08",
        "last_update" => "2023-03-08",
        "collaborators" => "No",
        "image" => "uploads/discord.png",
        "description" => "A clone of site Discord",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/htmlcss-discord.git",
    ],

    [
        "title" => "Boolando",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-08",
        "last_update" => "2023-03-09",
        "collaborators" => "No",
        "image" => "uploads/boolando.png",
        "description" => "A site of Boolando",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-boolando.git",
    ],

    [
        "title" => "Zoom",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-09",
        "last_update" => "2023-03-10",
        "collaborators" => "No",
        "image" => "uploads/zoom.png",
        "description" => "A clone of Zoom",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-zoom.git",
    ],

    [
        "title" => "Animation Filter",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-11",
        "last_update" => "2023-03-11",
        "collaborators" => "No",
        "image" => "uploads/animation.png",
        "description" => "Effects and other stuff",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-animation-filter.git",
    ],

    [
        "title" => "Dropbox",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-13",
        "last_update" => "2023-03-16",
        "collaborators" => "No",
        "image" => "uploads/dropbox.png",
        "description" => "Dropbox",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/htmlcss-dropbox.git",
    ],

    [
        "title" => "Wannabe",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-17",
        "last_update" => "2023-03-20",
        "collaborators" => "No",
        "image" => "uploads/wannabe.png",
        "description" => "Wannabe - Lezioni dove vuoi tu",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-resp-wannabe.git",
    ],

    [
        "title" => "Responsive Layout",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-20",
        "last_update" => "2023-03-22",
        "collaborators" => "No",
        "image" => "uploads/responsive.png",
        "description" => "Responsive",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/htmlcss-responsive-layout.git",
    ],

    [
        "title" => "Spotify Web",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "No",
        "image" => "uploads/spotifyweb.png",
        "description" => "A clone of the spotify web interface",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-spotifyweb.git",
    ],

    [
        "title" => "12 Bool",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-27",
        "last_update" => "2023-03-27",
        "collaborators" => "No",
        "image" => "uploads/bool.png",
        "description" => "12 bool",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-12bool.git",
    ],

    [
        "title" => "Human",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-03",
        "last_update" => "2023-04-03",
        "collaborators" => "No",
        "image" => "uploads/human.png",
        "description" => "Human Code",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/human-code.git",
    ],

    [
        "title" => "Bootstrap Dashboard",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-30",
        "last_update" => "2023-04-04",
        "collaborators" => "No",
        "image" => "uploads/bootdash.png",
        "description" => "Bootstrap Dashboard",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-bootstrap-dashboard.git",
    ],

    [
        "title" => "Wannabe",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-04",
        "last_update" => "2023-04-04",
        "collaborators" => "No",
        "image" => "uploads/jswannabe.png",
        "description" => "Wannabe",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-pwdgen-wannabe.git",
    ],

    [
        "title" => "Biglietto del Treno",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-14",
        "last_update" => "2023-04-14",
        "collaborators" => "No",
        "image" => "uploads/train.png",
        "description" => "Train Ticket",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-biglietto-treno-form.git",
    ],

    [
        "title" => "Biglietto Treno",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-05",
        "last_update" => "2023-04-14",
        "collaborators" => "No",
        "image" => "uploads/jstrain.png",
        "description" => "JS Train Ticket",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-biglietto-treno.git",
    ],

    [
        "title" => "Fizz Buzz",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-15",
        "last_update" => "2023-04-15",
        "collaborators" => "No",
        "image" => "uploads/fizzbuzz.png",
        "description" => "Fizzbuzz",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-fizzbuzz.git",
    ],

    [
        "title" => "Bootstrap Freelance",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-15",
        "last_update" => "2023-03-28",
        "collaborators" => "No",
        "image" => "uploads/freelance.png",
        "description" => "Bootstrap Freelance",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/html-css-bootstrap-freelancer.git",
    ],

    [
        "title" => "Mail Dadi",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-17",
        "last_update" => "2023-04-17",
        "collaborators" => "No",
        "image" => "",
        "description" => "Mail Dadi",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-mail-dadi.git",
    ],

    [
        "title" => "Snack Blocco",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-18",
        "last_update" => "2023-04-18",
        "collaborators" => "No",
        "image" => "",
        "description" => "Snack Blocco 2",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-jsnacks-blocco-2.git",
    ],

    [
        "title" => "Lista Spesa",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-19",
        "last_update" => "2023-04-19",
        "collaborators" => "No",
        "image" => "uploads/lista.png",
        "description" => "Lista Spesa",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-lista-spesa.git",
    ],

    [
        "title" => "Pali e Dispari",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-20",
        "last_update" => "2023-04-20",
        "collaborators" => "No",
        "image" => "",
        "description" => "Pali e Dispari",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-paliedispari.git",
    ],

    [
        "title" => "Campo Minato Grid",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-21",
        "last_update" => "2023-04-22",
        "collaborators" => "No",
        "image" => "campominatogrid.png",
        "description" => "Campo Minato Grid",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-campominato-grid.git",
    ],

    [
        "title" => "Campo Minato Dom",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-26",
        "last_update" => "2023-04-27",
        "collaborators" => "No",
        "image" => "uploads/campominatodom.png",
        "description" => "Campo Minato Dom",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-campominato-dom.git",
    ],

    [
        "title" => "Simon",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-28",
        "last_update" => "2023-04-28",
        "collaborators" => "No",
        "image" => "uploads/simon.png",
        "description" => "Simon",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-simon.git",
    ],

    [
        "title" => "Our Team",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-30",
        "last_update" => "2023-05-02",
        "collaborators" => "No",
        "image" => "uploads/ourteam.png",
        "description" => "OurTeam",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-our-team.git",
    ],

    [
        "title" => "Object Carousel",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-02",
        "last_update" => "2023-05-02",
        "collaborators" => "No",
        "image" => "uploads/carousel.png",
        "description" => "Object Carousel",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-array-objects-carousel.git",
    ],

    [
        "title" => "Social Post",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-03",
        "last_update" => "2023-05-04",
        "collaborators" => "No",
        "image" => "uploads/socialpost.png",
        "description" => "A Facebook clone",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-social-posts.git",
    ],

    [
        "title" => "Hello",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-08",
        "last_update" => "2023-05-08",
        "collaborators" => "No",
        "image" => "uploads/hello.png",
        "description" => "Hello",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vue-hello.git",
    ],

    [
        "title" => "Slider",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-08",
        "last_update" => "2023-05-08",
        "collaborators" => "No",
        "image" => "uploads/slider.png",
        "description" => "Slider",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vue-slider.git",
    ],

    [
        "title" => "Todolist",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-09",
        "last_update" => "2023-05-10",
        "collaborators" => "No",
        "image" => "uploads/todolist.png",
        "description" => "Todolist",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vue-todolist.git",
    ],

    [
        "title" => "Boolzapp",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-10",
        "last_update" => "2023-05-16",
        "collaborators" => "No",
        "image" => "uploads/boolzapp.png",
        "description" => "A Whatsapp clone",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vue-boolzapp.git",
    ],

    [
        "title" => "Email List",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-16",
        "last_update" => "2023-05-17",
        "collaborators" => "No",
        "image" => "uploads/emaillist.png",
        "description" => "Email List",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vue-email-list.git",
    ],

    [
        "title" => "Hello World - Vite",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-17",
        "last_update" => "2023-05-17",
        "collaborators" => "No",
        "image" => "uploads/hellovite.png",
        "description" => "Prima volta con Vite",
        "technologies" => [1, 2, 4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vite-hello-world.git",
    ],

    [
        "title" => "DC-Comics - Vite",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-18",
        "last_update" => "2023-05-19",
        "collaborators" => "No",
        "image" => "uploads/comicsvite.png",
        "description" => "Comics con Vite",
        "technologies" => [1, 2, 4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vite-comics.git",
    ],

    [
        "title" => "Yu-Gi-Oh - Vite",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-22",
        "last_update" => "2023-05-24",
        "collaborators" => "No",
        "image" => "uploads/yugioh.png",
        "description" => "Yu-Gi-Oh con Vite",
        "technologies" => [1, 2, 4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/vite-yu-gi-oh.git",
    ],

    [
        "title" => "Badwords",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-06",
        "last_update" => "2023-06-06",
        "collaborators" => "No",
        "image" => "uploads/badwords.png",
        "description" => "Badwords censurated",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/php-badwords.git",
    ],

    [
        "title" => "Hotel",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-07",
        "last_update" => "2023-06-07",
        "collaborators" => "No",
        "image" => "",
        "description" => "Hotel",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/php-hotel.git",
    ],

    [
        "title" => "Strong Password Generator",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-07",
        "last_update" => "2023-06-09",
        "collaborators" => "No",
        "image" => "",
        "description" => "Strong Generator of Passwords",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/php-strong-password-generator.git",
    ],

    [
        "title" => "Dischi",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-09",
        "last_update" => "2023-06-09",
        "collaborators" => "No",
        "image" => "",
        "description" => "Dischi",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/php-dischi-json.git",
    ],

    [
        "title" => "First Database",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-12",
        "last_update" => "2023-06-12",
        "collaborators" => "No",
        "image" => "",
        "description" => "First Database",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/db-first.git",
    ],

    [
        "title" => "University Database",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-13",
        "last_update" => "2023-06-15",
        "collaborators" => "No",
        "image" => "",
        "description" => "University Database",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/db-university.git",
    ],

    [
        "title" => "PHP OOP 1",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-19",
        "last_update" => "2023-06-20",
        "collaborators" => "No",
        "image" => "",
        "description" => "PHP OOP 1",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/php-oop-1.git",
    ],

    [
        "title" => "PHP OOP 2",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-20",
        "last_update" => "2023-06-21",
        "collaborators" => "No",
        "image" => "",
        "description" => "PHP OOP 2",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/php-oop-2.git",
    ],

    [
        "title" => "Laravel - Primi Passi",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-22",
        "last_update" => "2023-06-22",
        "collaborators" => "No",
        "image" => "",
        "description" => "PHP OOP 2",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-primi-passi.git",
    ],

    [
        "title" => "Template - Base",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-23",
        "last_update" => "2023-06-23",
        "collaborators" => "No",
        "image" => "",
        "description" => "Esempio di Template Laravel",
        "technologies" => [4, 5],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/template.git",
    ],

    [
        "title" => "Laravel Comics",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-23",
        "last_update" => "2023-06-23",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel Comics",
        "technologies" => [4, 5],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-comics.git",
    ],

    [
        "title" => "Boolflix",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-24",
        "last_update" => "2023-06-26",
        "collaborators" => "No",
        "image" => "",
        "description" => "The Clone of Netflix",
        "technologies" => [4, 5],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/vite-boolflix.git",
    ],

    [
        "title" => "Laravel Migration Seeder",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-27",
        "last_update" => "2023-06-27",
        "collaborators" => "No",
        "image" => "",
        "description" => "Migration Seeder",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-migration-seeder.git",
    ],

    [
        "title" => "Esercizio Brance",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-28",
        "last_update" => "2023-06-28",
        "collaborators" => "Paolo Falco,Vincenzo Minardi, Antonio D'Angelo, Luca Casamassima",
        "image" => "",
        "description" => "First exercice of Merge",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/esercizio-branche.git",
    ],

    [
        "title" => "Laravel Model Controller",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-26",
        "last_update" => "2023-06-29",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel Model Controller",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-model-controller.git",
    ],

    [
        "title" => "Laravel Boolean",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Paolo Falco, Antonio Nicolaci, Alessandra Casu, 
        Gary Smith Alvarez Venturo, Renato Taccogna, Pierluca Strianese",
        "image" => "uploads/laravelboolean.png",
        "description" => "A invoices organizer",
        "technologies" => [6, 7],
        "type_id" => 3,
        "link_github" => "https://github.com/Paolo96700/laravel-boolean.git",
    ],

    [
        "title" => "DC Comics",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-29",
        "last_update" => "2023-07-07",
        "collaborators" => "No",
        "image" => "uploads/dccomics.png",
        "description" => "A Dc Comics site homepage clone",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-dc-comics.git",
    ],

    [
        "title" => "Laravel Auth",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-05",
        "last_update" => "2023-07-08",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel Auth",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-auth.git",
    ],

    [
        "title" => "Laravel One To Many",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-10",
        "last_update" => "2023-07-11",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel One To Many",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-one-to-many.git",
    ],

    [
        "title" => "School Chess",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-07-13",
        "collaborators" => "No",
        "image" => "uploads/schoolchess.png",
        "description" => "Avada Driving clone",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/proj-html-vuejs.git",
    ],

    [
        "title" => "Laravel Many To Many",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-11",
        "last_update" => "2023-07-14",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel Many To Many",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-many-to-many.git",
    ],

    [
        "title" => "Boolfolio",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-14",
        "last_update" => "2023-07-18",
        "collaborators" => "No",
        "image" => "",
        "description" => "Boolfolio",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/vite-boolfolio.git",
    ],

    [
        "title" => "Laravel Api",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-14",
        "last_update" => "2023-07-19",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel Api",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-api.git",
    ],

    [
        "title" => "Router Frontoffice",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-21",
        "last_update" => "2023-07-21",
        "collaborators" => "Antonio NIcolaci, Paolo Falco, Cristian Lazzari, Gianluca Giardella, Vincenzo Minardi",
        "image" => "",
        "description" => "Router Front Office",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/laravel-vue-router-frontoffice.git",
    ],

    [
        "title" => "Router Backend",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-21",
        "last_update" => "2023-07-21",
        "collaborators" => "No",
        "image" => "",
        "description" => "Router Back End",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/laravel-vue-router.git",
    ],

];
