<?php

return [
        // HTML e CSS
    [
        "title"         => "My Project",
        "author"        => "Paolo Falco",
        "creation_date" => "2023-02-10",
        "last_update"   => "2023-02-11",
        "collaborators" => "No",
        "image"         => "img/my-project.png",
        "description"   => "The first project",
        "technologies"  => [1],
        "type_id"       => 1,
        "link_github"   => "https://github.com/Boolean-projects-paolo/Myproject",
        "link_netlify"  => "https://my-first-project-paolo.netlify.app/",
    ],

    [
        "title" => "Hello",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-23",
        "last_update" => "2023-02-23",
        "collaborators" => "No",
        "image" => "img/hello.png",
        "description" => "The hello project",
        "technologies" => [1],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/htmlcss-hello",
        "link_netlify"  => "",
    ],

    [
        "title" => "London Trip",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-24",
        "last_update" => "2023-02-27",
        "collaborators" => "No",
        "image" => "img/london.png",
        "description" => "My travel for London",
        "technologies" => [1],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-london-trip",
        "link_netlify"  => "https://london-site-paolo.netlify.app",
    ],

    [
        "title" => "Booleaner",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-27",
        "last_update" => "2023-03-01",
        "collaborators" => "No",
        "image" => "img/booleaner.png",
        "description" => "The Booleaner",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-booleaner",
        "link_netlify"  => "https://booleaner-paolo.netlify.app",
    ],

    [
        "title" => "Toboolist",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-28",
        "last_update" => "2023-03-01",
        "collaborators" => "No",
        "image" => "img/toboolist.png",
        "description" => "The Toboolist",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-toboolist",
        "link_netlify"  => "https://toboolist-paolo.netlify.app",
    ],

    [
        "title" => "Responsive",
        "author" => "Paolo Falco",
        "creation_date" => "2023-02-28",
        "last_update" => "2024-02-13",
        "collaborators" => "No",
        "image" => "img/responsive.png",
        "description" => "The Responsive",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/htmlcss-responsive-layout",
        "link_netlify"  => "https://responsive-paolo.netlify.app",
    ],

    [
        "title" => "Responsive Wannabe",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-01",
        "last_update" => "2024-03-20",
        "collaborators" => "No",
        "image" => "img/wannabe.png",
        "description" => "Wannabe - Lezioni dove vuoi tu",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-resp-wannabe",
        "link_netlify"  => "https://wnannabe-paolo.netlify.app",
    ],

    [
        "title" => "Float Cards",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-02",
        "last_update" => "2023-03-02",
        "collaborators" => "No",
        "image" => "img/floatcards.png",
        "description" => "The Floats Cards",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-float-cards",
        "link_netlify"  => "https://floats-card-paolo.netlify.app/",
    ],

    [
        "title" => "Struttura Discord",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-06",
        "last_update" => "2023-03-06",
        "collaborators" => "No",
        "image" => "img/strutturadiscord.png",
        "description" => "A first structure of site Discord",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/htmlcss-struttura-discord",
        "link_netlify"  => "",
    ],

    [
        "title" => "Discord",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-08",
        "last_update" => "2023-03-08",
        "collaborators" => "No",
        "image" => "img/discord.png",
        "description" => "A clone of site Discord",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/htmlcss-discord",
        "link_netlify"  => "https://discord-paolo.netlify.app/",
    ],

    [
        "title" => "Boolando",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-08",
        "last_update" => "2023-03-09",
        "collaborators" => "No",
        "image" => "img/boolando.png",
        "description" => "A site of Boolando",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-boolando",
        "link_netlify"  => "https://discord-paolo.netlify.app/",
    ],

    [
        "title" => "Zoom",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-09",
        "last_update" => "2023-03-10",
        "collaborators" => "No",
        "image" => "img/zoom.png",
        "description" => "A clone of Zoom",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-boolando",
        "link_netlify"  => "https://zoom-paolo.netlify.app",
    ],

    [
        "title" => "Animation Filter",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-11",
        "last_update" => "2023-03-11",
        "collaborators" => "No",
        "image" => "img/animations.png",
        "description" => "Effects and other stuff",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-animation-filter",
        "link_netlify"  => "https://animation-paolo.netlify.app",
    ],

    [
        "title" => "Dropbox",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-13",
        "last_update" => "2023-03-16",
        "collaborators" => "No",
        "image" => "img/dropbox.png",
        "description" => "Dropbox",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/htmlcss-dropbox",
        "link_netlify"  => "https://dropbox-paolo.netlify.app",
    ],

    [
        "title" => "Spotify Web",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "No",
        "image" => "img/spotifyweb.png",
        "description" => "A clone of the spotify web interface",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-spotifyweb",
        "link_netlify"  => "https://spotify-paolo.netlify.app",
    ],

    [
        "title" => "12 Bool",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-27",
        "last_update" => "2023-03-27",
        "collaborators" => "No",
        "image" => "img/bool.png",
        "description" => "12 bool",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-12bool",
        "link_netlify"  => "https://12-bools-paolo.netlify.app",
    ],

    [
        "title" => "Human",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-03",
        "last_update" => "2023-04-03",
        "collaborators" => "No",
        "image" => "img/human.png",
        "description" => "Human Code",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/human-code",
        "link_netlify"  => "",
    ],

    [
        "title" => "Bootstrap Dashboard",
        "author" => "Paolo Falco",
        "creation_date" => "2023-03-30",
        "last_update" => "2023-04-04",
        "collaborators" => "No",
        "image" => "img/bootdash.png",
        "description" => "Bootstrap Dashboard",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo/html-css-bootstrap-dashboard",
        "link_netlify"  => "https://bootdash-paolo.netlify.app",
    ],

    [
        "title" => "Esercizio Brance",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-28",
        "last_update" => "2023-06-28",
        "collaborators" => "Paolo Falco,Vincenzo Minardi, Antonio D'Angelo, Luca Casamassima",
        "image" => "",
        "description" => "First exercice of Merge",
        "technologies" => [1, 2],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/esercizio-branche.git",
    ],

        // Javascript
    [
        "title" => "Wannabe JS",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-04",
        "last_update" => "2023-04-04",
        "collaborators" => "No",
        "image" => "",
        "description" => "Wannabe",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-pwdgen-wannabe",
        "link_netlify"  => "https://wannabe-js-paolo.netlify.app",
    ],

    [
        "title" => "Biglietto Treno",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-05",
        "last_update" => "2023-04-14",
        "collaborators" => "No",
        "image" => "",
        "description" => "JS Train Ticket",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-biglietto-treno",
        "link_netlify"  => "https://js-train-paolo.netlify.app",
    ],

    [
        "title" => "Biglietto del Treno",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-14",
        "last_update" => "2023-04-14",
        "collaborators" => "No",
        "image" => "img/train.png",
        "description" => "Train Ticket",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-biglietto-treno-form",
        "link_netlify"  => "https://js-form-train-paolo.netlify.app",
    ],

    [
        "title" => "Fizz Buzz",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-15",
        "last_update" => "2023-04-15",
        "collaborators" => "No",
        "image" => "img/fizzbuzz.png",
        "description" => "Fizzbuzz",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-fizzbuzz",
        "link_netlify"  => "https://fizzbuzz-paolo.netlify.app",
    ],

    [
        "title" => "Mail Dadi",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-17",
        "last_update" => "2023-04-17",
        "collaborators" => "No",
        "image" => "",
        "description" => "Mail Dadi",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-mail-dadi",
        "link_netlify"  => "",
    ],

    [
        "title" => "Snack Blocco",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-18",
        "last_update" => "2023-04-18",
        "collaborators" => "No",
        "image" => "",
        "description" => "Snack Blocco 2",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-jsnacks-blocco-2",
        "link_netlify"  => "",
    ],

    [
        "title" => "Lista Spesa",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-19",
        "last_update" => "2024-02-13",
        "collaborators" => "No",
        "image" => "",
        "description" => "Lista Spesa con possibilità di aggiunta elementi",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-lista-spesa",
        "link_netlify"  => "https://fizzbuzz-paolo.netlify.app",
    ],

    [
        "title" => "Palindroma e Pari e Dispari",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-20",
        "last_update" => "2023-04-20",
        "collaborators" => "No",
        "image" => "",
        "description" => "Snack parole Palindrome e Pari - Dispari",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-paliedispari",
        "link_netlify"  => "",
    ],  

    [
        "title" => "Campo Minato Grid",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-21",
        "last_update" => "2023-04-22",
        "collaborators" => "No",
        "image" => "img/campominatogrid.png",
        "description" => "Campo Minato Grid",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-campominato-grid",
        "link_netlify"  => "https://campominato-grid-paolo.netlify.app",
    ],

    [
        "title" => "Campo Minato Dom",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-26",
        "last_update" => "2023-04-27",
        "collaborators" => "No",
        "image" => "img/campominatodom.png",
        "description" => "Campo Minato Dom",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-campominato-dom",
        "link_netlify"  => "campominato-dom-paolo.netlify.app",
    ],

    [
        "title" => "Simon",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-28",
        "last_update" => "2024-02-14",
        "collaborators" => "No",
        "image" => "img/simon.png",
        "description" => "Simon",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-simon.git",
        "link_netlify"  => "https://simon-paolo.netlify.app",
    ],

    [
        "title" => "Our Team",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-30",
        "last_update" => "2023-05-02",
        "collaborators" => "No",
        "image" => "img/ourteam.png",
        "description" => "OurTeam",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-our-team",
        "link_netlify"  => "",
    ],

    [
        "title" => "Object Carousel",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-02",
        "last_update" => "2023-05-02",
        "collaborators" => "No",
        "image" => "uploads/carousel.png",
        "description" => "Object Carousel",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Paolo96700/js-array-objects-carousel.git",
        "link_netlify"  => "https://carousel-js-paolo.netlify.app",
    ],

    [
        "title" => "Social Post",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-03",
        "last_update" => "2023-05-04",
        "collaborators" => "No",
        "image" => "uploads/socialpost.png",
        "description" => "A Facebook clone",
        "technologies" => [1, 2, 3],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-js/js-social-posts",
        "link_netlify"  => "",
    ],

        //Bootstrap

    [
        "title" => "Bootstrap Freelance",
        "author" => "Paolo Falco",
        "creation_date" => "2023-04-15",
        "last_update" => "2023-03-28",
        "collaborators" => "No",
        "image" => "uploads/freelance.png",
        "description" => "Bootstrap Freelance",
        "technologies" => [1, 2],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-bootstrap/html-css-bootstrap-freelancer",
        "link_netlify"  => "",
    ],

        //Vue.JS

    [
        "title" => "Hello",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-08",
        "last_update" => "2023-05-08",
        "collaborators" => "No",
        "image" => "img/hello.png",
        "description" => "Hello",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/vue-hello",
        "link_netlify"  => "",
    ],

    [
        "title" => "Slider",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-08",
        "last_update" => "2023-05-08",
        "collaborators" => "No",
        "image" => "img/slider.png",
        "description" => "Slider",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/vue-slider",
        "link_netlify"  => "https://vue-slider-paolo.netlify.app",
    ],

    [
        "title" => "Todolist",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-09",
        "last_update" => "2023-05-10",
        "collaborators" => "No",
        "image" => "img/todolist.png",
        "description" => "Todolist",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/vue-todolist",
        "link_netlify"  => "https://todolist-paolo.netlify.app",
    ],

    [
        "title" => "Boolzapp",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-10",
        "last_update" => "2023-05-16",
        "collaborators" => "No",
        "image" => "img/boolzapp.png",
        "description" => "A Whatsapp clone",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/vue-boolzapp",
        "link_netlify"  => "https://boolzapp-paolo.netlify.app",
    ],

    [
        "title" => "Email List",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-16",
        "last_update" => "2024-02-14",
        "collaborators" => "No",
        "image" => "uploads/emaillist.png",
        "description" => "Email List",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/vue-email-list",
        "link_netlify"  => "https://emaillist-paolo.netlify.app",
    ],

    [
        "title" => "Hello World - Vite",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-17",
        "last_update" => "2023-05-17",
        "collaborators" => "No",
        "image" => "uploads/hellovite.png",
        "description" => "Prima volta con Vite",
        "technologies" => [1, 2, 4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/vite-hello-world",
        "link_netlify"  => "",
    ],

    [
        "title" => "DC-Comics - Vite",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-18",
        "last_update" => "2023-05-19",
        "collaborators" => "No",
        "image" => "img/comicsvite.png",
        "description" => "Comics con Vite",
        "technologies" => [1, 2, 4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/vite-comics",
        "link_netlify"  => "https://vite-comics-paolo.netlify.app",
    ],

    [
        "title" => "Yu-Gi-Oh - Vite",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-22",
        "last_update" => "2023-05-24",
        "collaborators" => "No",
        "image" => "uploads/yugioh.png",
        "description" => "Yu-Gi-Oh con Vite",
        "technologies" => [1, 2, 4, 5],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/vite-yu-gi-oh",
        "link_netlify"  => "https://vite-yugioh-paolo.netlify.app/",
    ],

    [
        "title" => "Boolflix",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-24",
        "last_update" => "2023-06-26",
        "collaborators" => "No",
        "image" => "",
        "description" => "The Clone of Netflix",
        "technologies" => [4],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/vite-boolflix",
        "link_netlify"  => "https://boolflix-paolo.netlify.app",
    ],

    [
        "title" => "School Chess",
        "author" => "Paolo Falco",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-07-13",
        "collaborators" => "No",
        "image" => "uploads/schoolchess.png",
        "description" => "Avada Driving clone",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/proj-html-vuejs",
        "link_netlify"  => "https://proj-paolo.netlify.app",
    ],

    [
        "title" => "Router Frontoffice",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-21",
        "last_update" => "2023-07-21",
        "collaborators" => "Antonio NIcolaci, Paolo Falco, Cristian Lazzari, Gianluca Giardella, Vincenzo Minardi",
        "image" => "",
        "description" => "Router Front Office",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-paolo-vue/laravel-vue-router-frontoffice",
        "link_netlify"  => "",
    ],

        // PHP

    [
        "title" => "Badwords",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-06",
        "last_update" => "2023-06-06",
        "collaborators" => "No",
        "image" => "",
        "description" => "Badwords censurated",
        "technologies" => [6],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-PHP/php-badwords",
        "link_netlify"  => "",
    ],

    [
        "title" => "Hotel",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-07",
        "last_update" => "2023-06-07",
        "collaborators" => "No",
        "image" => "",
        "description" => "Hotel",
        "technologies" => [6],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-PHP/php-hotel",
        "link_netlify"  => "",
    ],

    [
        "title" => "Strong Password Generator",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-07",
        "last_update" => "2023-06-09",
        "collaborators" => "No",
        "image" => "",
        "description" => "Strong Generator of Passwords",
        "technologies" => [6],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-PHP/php-strong-password-generator",
        "link_netlify"  => "",
    ], 

    [
        "title" => "Dischi",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-09",
        "last_update" => "2023-06-09",
        "collaborators" => "No",
        "image" => "",
        "description" => "Dischi",
        "technologies" => [6],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-PHP/php-dischi-json",
        "link_netlify"  => "",
    ],

    [
        "title" => "PHP OOP 1",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-19",
        "last_update" => "2023-06-20",
        "collaborators" => "No",
        "image" => "",
        "description" => "PHP OOP 1",
        "technologies" => [6],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-PHP/php-oop-1",
        "link_netlify"  => "",
    ],

    [
        "title" => "PHP OOP 2",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-20",
        "last_update" => "2023-06-21",
        "collaborators" => "No",
        "image" => "",
        "description" => "PHP OOP 2",
        "technologies" => [6],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-PHP/php-oop-2",
        "link_netlify"  => "",
    ],

        // Database

    [
        "title" => "First Database",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-12",
        "last_update" => "2023-06-12",
        "collaborators" => "No",
        "image" => "",
        "description" => "First Database",
        "technologies" => [],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/db-first.git",
        "link_netlify"  => "",
    ],

    [
        "title" => "University Database",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-13",
        "last_update" => "2023-06-15",
        "collaborators" => "No",
        "image" => "",
        "description" => "University Database",
        "technologies" => [],
        "type_id" => 2,
        "link_github" => "https://github.com/Paolo96700/db-university.git",
        "link_netlify"  => "",
    ],

        // Laravel

    [
        "title" => "Laravel - Primi Passi",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-22",
        "last_update" => "2023-06-22",
        "collaborators" => "No",
        "image" => "",
        "description" => "PHP OOP 2",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-Laravel/laravel-primi-passi",
        "link_netlify"  => "",
    ],

    [
        "title" => "Template - Base",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-23",
        "last_update" => "2023-06-23",
        "collaborators" => "No",
        "image" => "",
        "description" => "Esempio di Template Laravel",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-Laravel/template",
        "link_netlify"  => "",
    ],

    [
        "title" => "Laravel DC Comics",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-23",
        "last_update" => "2023-06-23",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel DC Comics",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-Laravel/laravel-dc-comics",
        "link_netlify"  => "",
    ],

    [
        "title" => "Laravel Migration Seeder",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-27",
        "last_update" => "2023-06-27",
        "collaborators" => "No",
        "image" => "",
        "description" => "Migration Seeder",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-Laravel/laravel-migration-seeder",
        "link_netlify"  => "",
    ],

    [
        "title" => "Laravel Model Controller",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-26",
        "last_update" => "2023-06-29",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel Model Controller",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-Laravel/laravel-model-controller",
        "link_netlify"  => "",
    ],

    [
        "title" => "Laravel Boolean",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Paolo Falco, Antonio Nicolaci, Alessandra Casu, 
        Gary Smith Alvarez Venturo, Renato Taccogna, Pierluca Strianese",
        "image" => "",
        "description" => "A invoices organizer",
        "technologies" => [6, 7],
        "type_id" => 3,
        "link_github" => "https://github.com/Boolean-projects-Laravel/laravel-boolean",
        "link_netlify"  => "",
    ],

    [
        "title" => "DC Comics",
        "author" => "Paolo Falco",
        "creation_date" => "2023-06-29",
        "last_update" => "2023-07-07",
        "collaborators" => "No",
        "image" => "",
        "description" => "A Dc Comics site homepage clone",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-Laravel/laravel-dc-comics",
        "link_netlify"  => "",
    ],

    [
        "title" => "Laravel Auth",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-05",
        "last_update" => "2023-07-08",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel Auth",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-Laravel/laravel-auth",
        "link_netlify"  => "",
    ],

    [
        "title" => "Laravel One To Many",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-10",
        "last_update" => "2023-07-11",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel One To Many",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-Laravel/laravel-one-to-many",
        "link_netlify"  => "",
    ],

    [
        "title" => "Laravel Many To Many",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-11",
        "last_update" => "2023-07-14",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel Many To Many",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-Laravel/laravel-many-to-many",
        "link_netlify"  => "",
    ],

    

    // Progetti Completi Laravel + Vue

    [
        "title" => "Laravel Api",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-14",
        "last_update" => "2023-07-19",
        "collaborators" => "No",
        "image" => "",
        "description" => "Laravel Api",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-complete/laravel-api",
        "link_netlify"  => "",
    ],

    [
        "title" => "Boolfolio",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-14",
        "last_update" => "2023-07-18",
        "collaborators" => "No",
        "image" => "",
        "description" => "Boolfolio",
        "technologies" => [1, 2, 4],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-complete/vite-boolfolio",
        "link_netlify"  => "",
    ],

    [
        "title" => "Laravel Router Backend",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-21",
        "last_update" => "2023-07-21",
        "collaborators" => "No",
        "image" => "",
        "description" => "Router Back End",
        "technologies" => [6, 7],
        "type_id" => 2,
        "link_github" => "https://github.com/Boolean-projects-complete/laravel-vue-router",
        "link_netlify"  => "",
    ],

    [
        "title" => "Vue Router Frontoffice",
        "author" => "Paolo Falco",
        "creation_date" => "2023-07-21",
        "last_update" => "2023-07-21",
        "collaborators" => "Antonio NIcolaci, Paolo Falco, Cristian Lazzari, Gianluca Giardella, Vincenzo Minardi",
        "image" => "",
        "description" => "Router Front Office",
        "technologies" => [1, 2, 4],
        "type_id" => 1,
        "link_github" => "https://github.com/Boolean-projects-complete/laravel-vue-router-frontoffice",
        "link_netlify"  => "",
    ],

];
